# Generated by Django 6.0.1 on 2026-03-02 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('mech', 'Mechanical'), ('mba', 'MBA')], default='cse', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
