# Generated by Django 6.0.1 on 2026-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_notice_department_notice_is_pinned_notice_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
